(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 1500,
	height: 200,
	fps: 24,
	color: "#312C82",
	opacity: 1.00,
	webfonts: {},
	manifest: []
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.weed = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA+CtQABgKgEgYQgEgZgEgNIgIgXQgNAVgGAEQgEACgHAHIgNANQgTAQgKgGIgVgLIAKgBQAFABAHAFQAHACAKgLQAfgmAGAAQAEAAAGgLQgEgQgGgKQgDgGgCgHIgCgFIgmAbQgiAUgLgIIgSgPQAYAGALgGQAFgCAKgIQAJgIAGgDIAQgFIAJgFIAHgEQgFgMAAgFQAAgIgDAAIgHgDQgIgEgIABQgOACgOgMIgNgMIAbAFQADAAAIgCQAGgBAGADIARAKIACgVQABgFgCgIIgDgGQgOgEgQgBIgTgBQgIgCgGgEIgJgGIgBgDIALADQAMABAGgCQAPgEATADQADABAEADIADABQAGgQgBgCIgIAAIgUgDIgSgDQgEgBgGgGQgNgMABgBIAMAEIAUAGQAOADAWADIADABIAAgCIAAgGQgNABgLgIQgVgLACgEQAAgBAHADIAMAFIAXACQAFgBgBgFQgDgGAAgDIAAgPQAGAQADAAQACABABgGIAAgIIACgGIgIgGQAAAAAAAAQABAAAAAAQABgBABAAQAAAAABAAIAEABIgHgKQgBgCAJAEIgBgEIgCgHQABAAADADIAEAEIACgGQACgGABABQAEADgCAPIgDAKIgEAKQgBAIACAJQAFgCADgDIAGgHQABgBAAgBQABgBAAAAQABAAAAAAQAAABAAAAQgBAFgSAZIAAAFQgBAHgCAFQgCAFAGAAQAEgBgEAGQgOAQgBACQAAADADACQAOgNAFgJQAFgIAEgTQABgFAEAEQADADgBAJQgCAIgDAGIgKAQIgNARQgEAHgBAFQgDAWADAaQABAPAIAQIANgGQAFgBAJgDIAIAAQABAAAAAAQABAAAAAAQABgBAAAAQAAgBAAgBIAAgPIAGAIQAFAHgCAEQgFAIgRAKQgOAJAAABIACAMQADAMAEAJQAGANACAJIADAMQADAMgBALIAAApIgBADIgHABQABgCABgNg");
	this.shape.setTransform(8.3,18.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,37.7);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhZJMIAFgjIABgbIgDgfIgGgKQgVgGAAgPQgBgIAFgFQAFgHABgDIAEgKIALALQAFAGADAGIgBgnIgCgUQgIgEgBgIQgBgHgBgEIgJgOQgDACgIgBIgHgCQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAABgBAAIgKAIQgGAEgCgDQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAABgBIAEgLQAIgaAKgEQAFgDgEgGIAGAIIAIgFIAGgBIgDgMQgJgEAAgFQAAgKAJACQAGAAADgBIAAgBIACAEIAFAFQACACgBADQgBAGgLABIABAGIAAAEIAFgBIAGgCIABgBIAAgZQgJgGgEgHQgDgEAAgGIgBgFQgQgFgGgEQgJgHASgCIANgCIADgDQADgDAFAAQAKgBgGAJIgFAHIACACQACACABACQACAJgGgBIgHgCIgBADQAAAEACADQACAGAKAHIABgmQgBgQgBgBIgEgHQgEgHgBgFIgBgJQgKAAAAgJQAAgKAHAAIAJgBIAGgEIADgCIAAgDIgBgDQgSgTgCgKQgBgGAAgHIABgFQgJgIAEgFQADgDADABIAGAAIAIgEIAAABIAAAFIADAGQABAEgBADQgBADgDACQgBABgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAIgGgEIgBAGQgBAIACAEQADAFALAOIADADQAAgVgBgMIAAgiIgIhQQgJgGgFgHIgOgPIgCgCQAAAFgKgBQgGgBgIgFIgIgEIgTgEQgJgCgHgDQgHgEABgBQACgEAEgCQAEgCAFgGQABgFAEgDIAIgIIAFgBIAEgFIAFgEIAHgBIAEAAIgBAIQgBAJABADIAJATIAFADQAFADABADQACAFABAFIAHAKIABgJIgBgFQgEgCgBgDQAAgEADgDQADgDACACQAHAEgCAEIgEAHIgBAIQABAFgBADIALAIIACgFIABgDQgKgEACgGQAFgLAFAEQAEACAAAGIgCAIIgDAHIAAADIAEADIACghIgCgDQgDgEgBgBIADgCIADgCIgCggIgEgnQgPgNgCgGIgBgMIAAgGQgKgBAAgHQABgFAFgDIAGgCIAFgGQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIACAFIgBADIADABQADACAAAEQACAKgFgBIgKAAIgBAHQgBAHADADIANAOIAFg6IARhgIAHgYIADgNIACgGIACgJIAFgLQADgXADgJIADgOQgMACgFgDQgDgCgBgEQAAgDADgBIAKgHQAAgCgDgCQgLgMABgGQABgFAEAAIAEAAIAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAIALAIIgLgQQgHACgGgDIgHgEIgDgCIgEAAQgCgFgGABQgDABgGAEQgFADgDgBIgCgFQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgFABQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQgBgBAAgFIgBgIQgBgFAEgJQAEgJAHgEQAHgFAIgBQAGgBACABIAHAEIgBgEQgBgBAAgBQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQABAAAAABIACgDQACgCAEgBIAGgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQACADABAGIAFgGQAGgFADAAQAEAAAHAEIADgDQAEgDACABQAEABgKAKIAIAAQAHgBAAACQACAEgUAVIgFAEQgCACgDAAIgGABIABAFQABAFgCADQgCAFgEADIAFAGIACgBQADgBADABQADAAAAADQAAABAAABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIACAEQADABAPggIAVgvQADgKgKgFIgKgIQgBgCgBAAQgBgBAAgBQAAAAAAAAQAAgBABAAQAIAAAHAFQAFABADAEQACAFgCABIgCACIAAAGIAFgHQAGgHAGgEIARgJQABgHgBgDIgBgHQAAgEAEgBIAIgEQAFgBACADIAEAFQAAAAABABQAAAAAAAAQAAABAAAAQAAAAAAAAIgCADIAcgJQAIgBAGgEQABgEACgDIAFgFQgEgKAHgFQAEgEAEABIADACIACgCQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAABQABAAAAABQAAAAgBABQAAAAAAABIAAAEQgBAHgCABQgEAEgHABIgCABQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAAAIAAADQALABAGgDIAOgGQgBgHADgCIADgGQACgDADABQAFABACADIABgCQACgDADgCQADgBADABIADABIABgEQABgEACAAIAEgCIACACQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQgEAEAEgCIAHgDIABAAIgBAEQgBABAAABQAAAAAAAAQAAABgBAAQAAAAAAAAIACABQADABgBAEQAAAIgHgDIgGgEIgGADIgBAAIgBADIAGgBQAFAAADAEQACAEgEAEQgEADgDgBQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQgBgDgCgBIgEgCQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgPACgDACQgJAGAAABQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAIAGgCQAFgBADAEQAEAFgEAEQgGAFgGgFIABANQgBAJgCgCQgEgHgBgJIAAgHQgBgDgEgBQgFgBgQACQgEAAgLAFIgLADIAHABIAFgCQAGgDACADQADADAAAFQgBAEgGADQgIADgCgKIgFgCQgFgDgCABIgNAFQgMAFgHAFQgJAGgQAOIADgBQABAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAHgFABIgGABIgLASIgHARIACgBQAFAAAAACQABAEgBADQAAABgBAAQAAABAAAAQgBAAAAAAQAAAAgBgBIgCgCIgGABIgLAZIABAEQACAFAAAEQAAALgDAEIgGAGIgDAGIABADQABACgCADQgDAFgKAAIgDAHIADABQADAAACACQABADgBAFQgBAFgDAAIgGACIgCANIADACQAEAEgBADQgBAFgHgDIgLAgIgFARIAbABIADgEQAEgDAEAAQAFABABADIABAGQAAAJgIgBQgFAAgDgDIgCgEIgYgCIgFgBIgCAFIgIAkIADgDQAEgEAEAAQADgBACACQABAAAAABQABAAAAAAQABAAAAAAQABAAAAAAIAGgCIgFAKIgBAIQgBAFgEAAQgDABgEgDIgEgDIgEADIgIA3QgDAaACAnIAGgEQAAgFACgBQAEgCAEgBIAEgFIABgCQgLgKAEgFQAHgHAJAEQAEADADgGIACADIACAGIAAAIQAAAFgDABQgEADgJgDIgGAFIAGACQADABABAHQABAGgCAGIgEAHQAAABgBABQgBAAAAAAQgBAAAAABQgBAAAAgBIgHgBIgKAVIAAATIAHAAIAGgBQACAAABAEIACAGQAAgNAGADIALAFIAEABIAJAFQAHADAGACQACABgBAEIACABIADADQADAGgCADIgQADQgOAAgGACQgDABgGAJIgFAFIgQAXIACAjQAHgEACgFIADgDQgHgJACgFQABgCAEgBIAGgBIADgCIAEAFQAGAHgFAGQgDADgHgBIgKAOIALgHQAQgKADAAQACAAACgGQACgGAEgBIAHAAQADAAAFgDIAMgHQAFgDABgDIAFgFQABAAADADQAGAHAAAEIgDAGIAEACQADACgBAFIgCALQgBACgIgFIgFgCQgBgBgFABIgRAEQgKADgDgCIgDgCIgCAAQgJgBgLAJQgLAGgHADQACApgBAEQgBAFACAIIANgZIgDgGQgDgHADgBQACgDAFAAIAEABIAIgGIAEgCIgHANIACAEQABAEgDAEQgEAEgGgDIgQAbIAUgBIABABQACgCADABQAHAAADACQABAAAAABQABAAABAAQAAABAAAAQABAAAAgBIAFgCIgFAGIAAAFQAAAEgEADQgHAEgJgDIgTAPIgCAZQgBAIABAJQACACAFgCQACAAAGgEQAGgDAEACQAGADAHAIQAGAIgCACQgDACgGgDIgJgFIgPgFIgKgBIAAAjQABAOgDAZIAIAAQAHgCACgKQACgLgBgJIgBgHIgFgGQgDgFAHgCIAOgDIABACQAAACgBAEQgCAFgHADIAAANQABAOgCAEQgDAGgGAEIAYgFIgBgEQgBgEAEgBIAHgCIgBgHQgBgHACgCQACgBAHANIACgGQAEgGAIgCIAGgBIAFgHQAFgHAHAEQAMAHgBACIAFADQAFAFACAGQAEAJgDAFIgDAFIgFAYIgCALQgBACgFACQgEACgEgBIgDgBIABADQgCACgHgBIAFAJIAAAEIADAEQACAGgBADQgEAIABACQAAAAAAABQAAAAgBABQAAAAAAAAQAAAAgBABIgDABIABAHQACAGAFAEQADACAEAAQAAAAAAAAQABAAAAABQAAAAAAABQAAAAABABIAAASIgDAJIgBAFQAAADgFACIgGACIgEgCQgHgEgCgFIgEgLQgEAIgHAAQgEAAgGgDQgEgEAAgCIgDgHIgBAEQgCAGgFAEIgFAAIgSAIIAAAMIAKABQALABAFACQAIACADAAIgBgJQAAgIACgBQACgBADACIAKAJQAGAHAFAKQAFAJgCAAIgIgCQgIgDgCgDIgKgHIgbgEIgLAAIABAdQgBADAsAHIgDgKQgDgKAFgCQAHgDAHAEQAHADAEAHQADAJAAAHQAAAIgFgBQgFAAgIgDIgIgDIghgJIgLgFIgEAsIAWgNQgBgGAAgFQAAgKAGAAQAHABAFANQAFALgDAEQgEADgKgJIgbAPIgCAsQgBANgCAFgAhVHkIAFAPIAAgXIgFAIgAg4F0IgRAGIABAyIAPgHIAAgIQABgHAEgBIAIABIADAAIgCgLIAEgSIABgIIgSADgAhhFLQgEAMACAGQABACABAHIAFAJQABACAAAHQAAAGACABIAFAEIgCg2IgGgEIgDgCIgCAEgAg3E/IgUAWIABAhIAOgEQAJgEAKgCIABgCIADgDQAGgDABgCQgBgUAGgEIACgBIgBgBIgDgGQgBADgHgDQgFgCgBgDIgBgCIgEgBQgFABgEAEgAgxEoIgXAIIgFABIABAeIAKgJQAMgLAEgCIAHgDQACgCAAgIIgCgFIgGABgAhaE/IgDAEIAGAFIAAgMIgDADgAhdDLQgBAFACAEIAFAJIACgWIgHAAgAhVCxQgCAEABACIACAFIABgGIAAgJgAhKCrIASgNIgBgJIABgFQgEABgNgBgAhRAiIALgRQABgCgDgGIgFgIIgGgLgAhThYIABATIAHgLIgDgLIAAgCg");
	this.shape.setTransform(-9.1,58.9,1,1,0,0,0,-9.1,58.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.6,-58.9,39.3,117.9);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGExQAHhSgDgmIgHgxQgDgWABgOQAFgpgEgXQgBgFgBAAIgFAAQgLgEgEgEQgJgJAEAAIAPAGIAHgBIAAgIIgQgDQgHAAgDgCIgFgFIgJgGIADgBQABAAABAAQAAAAABABQAAAAABAAQAAABABAAIABAEQAAAAAAAAQAAAAABAAQAAAAABAAQABAAABAAIASAAQgTgEgGgGQgHgHAAgHIADgEIAAgBIgEgDIgLgHQgJgJAGADIALAEIAJACQAEAAABACQAAAAABABQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAABIALAJIAMAEQgBgLgCgCIgBgGQgOgKgFgIQgDgFgCgHQgCgIACABQADgBAFANQADAEALAFQgDgLABgHIAAgKIgDgDIgDgFIAAgCIAEABIgCgCIgGgFIgHgDQgBAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAAAIABgDIAEADIAMADIgEgGQgFgGgDgDIgIgDQgFgCgBgCIgDgGIABAAIAFABIAHAFIgNgTIgJgIQgEgFAAgGIgBgKIACAGQADAEAEADIAGAEIgEgRIACAAIAEADIAEAGIABAFQAHgNADgCQAAAAABgBQAAAAABAAQAAAAABABQAAAAAAABQABACgCAFQgCAFAAAOIACAJIAAAIQAFgNAGgEIAIgFIAAAEQAAAFgDADQgGAKgBAJQgBAJAGAGIACgLIADgEQAKgkgCgQIgDgSQgCgGgFgFQgKgMgOABQgTgCgEgFIgDgEIAGADQACABAIgBQgCgEAAgCQABgBAFACIAGADIgCgFIgBgCQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABABIAHAFQgBgJACABQADAAAEAJQACAEABAAIABgFQAAgBABgBQAAgBAAAAQABgBAAAAQAAAAABAAQABABABAHIABAHIACgGQAAgBABgBQAAAAAAgBQABAAAAAAQAAAAAAABIACAFIABAIQgBACABgBQABgBAAAAQAAAAABAAQAAgBABABQAAAAAAAAQACADABAHQAFgIACgTQACgcgHgTIgJgYIAHgDIAGAQQAFARACAPQAEAYgKAhIAAAKQAAABAAABQAAAAAAAAQAAABAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAAAAAAAQAAAAACAIIABAGIADgGIACACQACgCgBgGIABgGIACgBIADAHQADAEAAACQAFgHAEgDQABAAAAAAQABgBAAABQABAAAAAAQAAABABABQAAAAAAABQAAAAAAABQABAAgBABQAAABAAAAIAHgGIADgEIgBAHQAAABAAAAQABABAAAAQABAAABgBQAAAAACgBIAGgDQAAgBAAAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQgDAEALgGQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIgCABQAAABAAAAQAAAAAAAAQAAAAABAAQABAAABAAQAGgBACABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQgBADgGABQgEAAgNAAQgNABgOALQgaAWgHAPQgDAJALgOIAAAIQgBAJgCAEQgEAGgHAIIAAAGIAEgBQAAAAABAAQABAAAAAAQAAAAAAAAQAAABAAAAQgBACgEADIgCAFIgCAOIAAAKQAGgJADgBIADgBQAFgMACgCQAAAAAAAAQAAAAAAAAQAAABAAABQAAAAAAACIAAAEIAHgEQAAgBAAAAQABAAgBABQAAAAAAABQgBAAgBABIgGAIIgNAWIgBAEIADAIQAGgFAHgEIAKgFIACgJIAAgEQAAAAAAABQABAAAAAAQABAAABgBQAAAAABgBIAHgKQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQABAAAAAAQAAAAABgBQAAAAABgBQAAAAAAgBQABgFACAAIACABIgGAUIgEAGIgFAJQgEAHABADQALgVAGgIIAHgLIADgHIACAFQABADgBACQgDADAIACIgFADQgFAGgCAEIgIAWQAFgGAHgCIALgGIAIgGQACgBAAAEIgCAFIgGAIIAFABQAFABABACQACACgHAAQgEAAgSAGQgVAIgNAPQgMANAAAKIgCAHQASgJAHgBQAVgKABADQAAAGgXAHQgMAFgGAIQgBAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABIAAALIAAARQABANgBAGIgCAZIABATIADAVQADATABA3QABAigEAzgAgzgZQgBAEALAGQAFADALAFQgJgHgCgEIAAgCIABgBIAHAGIAEAEIABgDQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBIgYgJIgCACgAgGghIgEAFIABAGQAAAEAFACQABACADAAQACgSADgEQADgEABgFIgPAMg");
	this.shape.setTransform(79.5,93.5,1,1,0,0,0,0,29.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(72,33.5,15,61);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag6A8IgCgCIAGgDQAKgFAIgMIAHgJQgLAAgDgCIgOgEQgLgEAAgGIgBgKIACADIABAGQABAEAHABQAXAEABACQAAACAGAAQAFgGADgFIAFgIIgUgHQgRgIACgHIABgLIACAGQADAGADACIAIAEQAFABACACIALAGIADACIAGgFQABAAAAgBQABAAAAAAQAAgBAAAAQAAAAAAgBQAAgGgDgFQgFgFACgJIABgIIAFAMIADAEQABACAAADIAAAKIAIgEQAEgCADgFIgGgOQgGgKABgFIAAgGIACAFQACAFADACQAGAGACAHIACAGIAHgCIgGgNIgDgIIABgGIACgHQAAADADAMIAHAQIABACIAAgBIADgBQgDgFgBgHQgBgLACgBQABAAACAKQACAHADADQAAABAAAAQABAAAAAAQABAAAAAAQAAAAABgBIADgDIAFgEIgEAIQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAABAAIADgCIADgBIAAgFIACADIACgFIABAEIAEgEIgBAFIADgBQAAAAABAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAADgGACIgJADIgGAEIAEACIAEABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgCABgOgCQgDADgEABQgBAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAgBAAIgKgBIgCACIANADQAFAAAIgDQAAAAABgBQAAAAAAABQABAAAAAAQAAAAAAABQgBACgEACQgEACgLgBIgJAAIgGABQgJAEgIAGQgGAEgEAIIAGADIAFAFIABAEQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAEgEQgCAIgCAAQgCAAgJgEIgIgDIgKALIgHAJIgDAEQgEAFgEACIgKAFg");
	this.shape.setTransform(7.1,6.1,1,1,0,0,180);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhSBGIgCgEIAIgCQANgHALgMIAKgKQgOgCgDgDIgQgHQgNgHAAgHIABgMIADADQABADgBAFQAAAFAIACQAbAIABADQABACAHABQAHgGADgGIAIgJIgWgMQgTgNACgJIADgNIACAIQADAIADADIAJAFQAGADADADIALAKIADACQAFgDAEgCQABgBABAAQAAAAABgBQAAAAAAgBQAAAAAAgBQABgIgEgGQgEgIADgKIADgLIAEAQIADAGQAAACAAAFIAAAMIAKgDQADgCADgDIADgDQgCgJgDgJQgFgPABgGIACgHIABAGQACAIADACQAGAIACAKQABAGgBACQAJAAABgCIgFgRIgDgLIACgHIADgJIADAUIAFAWIABABIAAAAIAEgBQgEgHABgJQABgPACAAQACAAgBANQADAJACAEQAAABABABQAAAAABAAQAAAAABAAQAAAAABgBIAEgEIAHgDIgDADQgDAEAAACQAAABAHgDIAEgBIABgFIACAEIADgHIABAFIAFgEIgCAFIAEAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAAAQAAADgIADQgFABgHAAQgEABgEAEIAEADIAFABQAAABABAAQAAAAABAAQAAAAAAAAQAAAAgBAAQgCABgRgDIgCABIgHABQgBABAAAAQgBAAAAABQAAAAAAABQAAAAAAABQABABAAAAQAAAAgBAAQAAABgBgBQAAAAgBAAIgMgDQgBAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABQAJAEAGAAQAHABAIgCQABgBAAAAQABAAAAABQAAAAAAAAQAAABAAAAQgBADgEACIgIABIgLgBQgQgEgCABIgXALQgHAFgHAIIAGAGIAGAGIABAEQAAABABAAQAAABAAAAQAAAAABAAQAAAAABgBIAGgEIgCAFQgCAGgDgBQgFAAgIgHIgJgFQgGADgIAKIgJAKQgJAJgHADIgMAFg");
	this.shape_1.setTransform(21.9,9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.9,16.1);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAeArQgVgGgFgDIgMgHIgLAAIgKgBQgIgBgDgCIgMgMQgLgEgEgHQgCgDADgCIADgBQgGgHADgFIAEgFIACgBQABgGABgCIAIgEIANgGIANgCQADABADACQADACAAADQgBAcACgIIABgJQADgKAIgFQACgCAEACIAFgCQAEgBACAAQAPAFAFAAQAEAAAGAHIAIAGIAIAHQAIAJAAAGIgBAJQAAAEgFADQgGAFgJACIAFgBQAHAAAAADQAAAKABACQADAFgJADIgJACIgFAAQgGAAgFgBg");
	this.shape.setTransform(6.9,4.5,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,13.9,9);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AAemlIg7NL");
	this.shape.setTransform(3,42.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,8.1,86.5);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AASAFIAAgCIgqgHIACgBIAnAGIACgBQACgBADABQAAAAABAAQAAAAAAABQgBAAAAABQAAAAgBABQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIAAAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAg");
	this.shape.setTransform(10.8,9.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAAIQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIAAgCIgHgMIACABIAFAJIAFgBQAAAAABABQAAAAABABQAAAAAAABQAAAAABABQAAABgBAAQAAABAAAAQgBAAgBAAQAAABgBAAIgDABIgBgBg");
	this.shape_1.setTransform(8.8,9.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgBAIQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIACgBIACAAIAEgOIABACIgFALIADACQAAABABABQAAAAgBABQAAAAAAABQgBAAAAABIgCAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAgBgBg");
	this.shape_2.setTransform(7.3,9.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAFABIgOACIABgCIAMgBQgBAAAAAAQAAAAAAAAQAAgBABAAQAAgBAAAAQACgCADACQABAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABIgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBg");
	this.shape_3.setTransform(8.9,7.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAIAHIgJgHQgBAAAAAAQAAAAgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIACgBIABgBQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABgBABIAMAIg");
	this.shape_4.setTransform(6.7,7.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMAGIgBgBIACgCQAAgBABAAQAAAAAAAAQABAAAAAAQAAAAAAABIABABIAagMIAAABIgaALQADADgFABQAAAAgBABQAAAAgBgBQAAAAAAAAQAAgBAAAAIgFACg");
	this.shape_5.setTransform(6.4,8.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAAAPQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAgBgBgBQAAAAABAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAAAAIAAgdIAAAAIAAAdIABAAQABAAAAAAQAAABAAAAQABABAAAAQAAABgBAAQAAABAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAIAAAFg");
	this.shape_6.setTransform(8,10.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgQAHIAbgJIAAgEQABgCAEAAQABAAAAABQAAAAAAABQABAAgBABQAAABAAABIABABQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBIgeAKg");
	this.shape_7.setTransform(9.8,7.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AACARQgBgBAAAAQAAAAAAgBQAAAAAAAAQAAgBABAAIABgBIgMgeIACABIAKAbIAEAAQABAAAAAAQABABAAAAQAAABAAAAQABABAAABQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAgBAAIgCABIgBgBg");
	this.shape_8.setTransform(8.7,10.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSADQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBIABAAIAAgBIACgCQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAfABIgBABIgdgCQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgCABIgDgBg");
	this.shape_9.setTransform(5.7,8.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAKAQIgOgZQAAAAgBAAQgBAAAAABQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIACgBIABAAQABgBAAAAQAAAAABAAQAAABAAAAQAAAAABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAIAPAcg");
	this.shape_10.setTransform(6.5,6.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgEAYIAEgpQAAAAAAAAQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBgCACgDQAAAAABgBQAAAAAAAAQAAAAAAAAQAAABAAAAIACABIABAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIgEAqg");
	this.shape_11.setTransform(8.3,6.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgFAQQAAAAgBAAQgBAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABgBIACAAIAKgdIABACIgKAbIACACQAAABAAABQAAAAAAABQAAAAAAABQAAAAgBABIgBABQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBgBg");
	this.shape_12.setTransform(6.8,10.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAEASIgEgeQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAIABABIAAgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABQAAABgBAAQAAAAAAABQgBAAgBAAIAFAgg");
	this.shape_13.setTransform(7.2,6.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgKgDQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAIABgBIABgBQAAgBAAAAQABAAAAAAQAAgBAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAABQAAABAAABIAcANIgCABg");
	this.shape_14.setTransform(5.8,7.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRADIAdgDQAAAAAAAAQAAAAAAgBQAAAAAAgBQABAAAAAAQACgCADABQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBAAQABAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAgBAAAAIggAEg");
	this.shape_15.setTransform(9.5,8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAHAOQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIABgBIgVgXIACAAIATAVIAEgCQABAAAAAAQABABAAAAQABABAAAAQAAABAAABQABAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgCAAg");
	this.shape_16.setTransform(9.2,10);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAMAJQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgCIgcgNIABAAIAbAMIACgDQABgBAAAAQABAAABABQAAAAABAAQAAABABABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAIgBAAg");
	this.shape_17.setTransform(9.7,9.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLAPIAQgYQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABACIABABQABABAAAAQAAAAAAAAQABABAAAAQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAgBgBIgSAag");
	this.shape_18.setTransform(9.2,6.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AALAdIgRg0QgBAAgBABQAAAAgBgBQAAAAgBAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAAAAAgBQABAAAAAAIABgBIABABIABgBQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIAQA0g");
	this.shape_19.setTransform(6.5,5.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaAIIAAgCIgEACIAEgCIAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIABABIA1gOIAAABIg1AOQACADgEAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_20.setTransform(4.7,9.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAYACIAAgCIg4ABIAAgBIA4AAIAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAgBAAIAFAAIgFAAQABAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIgBAAIgBgBg");
	this.shape_21.setTransform(11.1,8.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAXAQQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAgBgBQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAABgBIAAgBIgtgfIABAAIAtAeIABgBQAAAAABgBQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABgBAAQAAAAgBABIAEACg");
	this.shape_22.setTransform(10.3,10.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgTAUQgBgBAAAAQAAAAAAgBQgBAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAAAAAQABABAAAAIABABIAngnIAAAAIgnAnIACABQAAABAAAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgDADg");
	this.shape_23.setTransform(5.4,10.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgXgHQAAAEgEgCQAAgBAAAAQAAAAgBAAQAAAAAAgBQAAAAABAAIAAgCIABgBQAAgBAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAgBABIA0ATIAAABg");
	this.shape_24.setTransform(4.9,7.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgYAPQgBgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAABQABAAAAAAIAAABIAvgcIAAAAIguAdQABAAAAABQAAABAAAAQAAABgBAAQAAABgBAAIgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAg");
	this.shape_25.setTransform(5.2,10);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAaAYIgsgoQAAAAgBABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAQAAgBABAAIAAgBIgDgDIAEADIABgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAABAAQABABAAAAQAAAAAAABQAAAAAAABQgBAAAAABIArApg");
	this.shape_26.setTransform(5.2,6.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAYAPQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIABgBIg3gZIABAAIA2AYIABgCQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAIAEACIgEgBQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgCAAg");
	this.shape_27.setTransform(11.1,10.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgRAcIAfgzQgBAAgBgBQgBAAAAgBQAAAAAAgBQABAAABgBQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIABABIACABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBgBQAAAAgBgBIgfA0g");
	this.shape_28.setTransform(9.6,5.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAWAbIglgvIgEACQgCAAgBgEQAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACAAIACgBQAAgBABAAQAAAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAIAmAxg");
	this.shape_29.setTransform(5.7,6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAUAdQAAABgBABQAAAAgBAAQAAAAgBAAQgBgBAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBIABgBIgog5IAAgBIApA5IACgBQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABQABABAAABQAAAAgBABQAAAAgBABQAAAAgBAAIADAFg");
	this.shape_30.setTransform(10.1,12.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAEApIgEhGQgEABAAgFQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIACAAIAAgFIAAAFIABAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABABAAQABAFgEgBIAFBGg");
	this.shape_31.setTransform(7.3,4.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgHAjQgEABAAgEQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAIACABIARhFIABABIgSBEIADAAQAAABAAAAQABABAAAAQAAABAAABQgBAAAAABQAAABgBAAQAAAAgBAAQAAAAgBAAQgBAAAAgBIgBAEg");
	this.shape_32.setTransform(6.3,12.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAAAkQgCABgBgEQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABgBIABAAIAAhHIAAAAIAABHIACAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAABgBAAQAAABAAAAQgBAAgBAAQAAAAgBAAIAAAGg");
	this.shape_33.setTransform(7.8,12.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAMAhQAAABgBAAQgBABAAgBQgBAAAAAAQgBgBAAgBQgBAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIACAAIgZhDIABAAIAZBCIACgBQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIACAGg");
	this.shape_34.setTransform(9.3,12.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgfAQIgBgCIgFADIAFgDQgDgDAEgCQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAIABACIBBgcIAAABIhBAcQAEAEgFABIgBABQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBAAAAg");
	this.shape_35.setTransform(4.2,10.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgbgFQAAAEgEgCQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIAAgCIgFgBIAGABIAAgCQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABABQABAAAAAAQABAAAAABQAAAAAAABQAAABgBABIBBARIAAABg");
	this.shape_36.setTransform(3.9,7.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAeADIAAgCIhHgEIAAgBIBHAEIAAAAQABAAAAgBQAAAAABAAQAAgBABAAQABAAABABQAAAAABAAQAAABAAAAQABAAgBAAQAAAAAAABIAFAAIgFABQABADgFAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAg");
	this.shape_37.setTransform(12.1,9.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgmAOIBDgXIgCgCQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAGgCIgGACQABABABABQAAAAAAABQAAAAgBABQgBAAgBABQgDACAAgFIhDAYg");
	this.shape_38.setTransform(11.7,6.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgaAEIgBgCIABgCIAAAAIABgBQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAAIAygDIgBABIgwACIgBADIgCABIgCAAg");
	this.shape_39.setTransform(5,8.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAVASIglgeQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgCIACgBIABgBIACgBQAAAAAAABQABAAAAAAQAAABAAAAQgBABAAABIAnAfg");
	this.shape_40.setTransform(5.5,6.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAeANQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIABgCIhEgUIABgBIBDAUIABgCQAAAAAAgBQABAAAAAAQABAAAAAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAAAQAAABgBABIAGABIgGgBQAAABAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgCAAg");
	this.shape_41.setTransform(11.8,10);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgcAdIAygxQgFgDAEgDQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAIABACIADgEIgDAEIABABQAAABABAAQAAAAAAABQAAAAgBABQAAAAAAABQgBABAAAAQgBAAgBAAQAAAAgBAAQAAgBgBgBIgyAxg");
	this.shape_42.setTransform(10.8,5.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AACAaIABgCIABgBIgMgxIABABIAMAvIADgBQAAABAAAAQABAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBgBQgBAAAAAAIgCABIgCgBg");
	this.shape_43.setTransform(8.8,11.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AACAbIgCgxQAAAAAAAAQAAABAAgBQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAAABIABAAIACABQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIACAzg");
	this.shape_44.setTransform(7.5,5.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAAAbQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAAAABgBQAAAAAAAAQAAAAABgBIABAAIADgyIABABIgEAwIACABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABIgCABIAAgBg");
	this.shape_45.setTransform(7.5,11.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AAUAPIgBgCIAAgBIgrgZIACgBIApAYIACgCQABAAAAAAQABAAAAAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgBAAg");
	this.shape_46.setTransform(10.3,10.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AALAZIgRgtIgDABQAAAAgBgBQAAAAAAAAQgBgBAAgBQAAAAAAgBIACgBIACAAIABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABIARAvg");
	this.shape_47.setTransform(6.7,6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgaAHIAwgJIAAgEQAAAAABAAQAAgBAAAAQABAAABAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBABQABAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgxAKg");
	this.shape_48.setTransform(10.5,7.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgMAZIAUgsQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAQABAAAAABIABABIABABQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAIgVAtg");
	this.shape_49.setTransform(9,5.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AAMAWQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgCIgegnIACAAIAdAmIADgBQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABQABAAgBABQAAAAAAAAQAAAAgBABQgBAAgBAAIgBABIgCAAg");
	this.shape_50.setTransform(9.6,10.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgEAhQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIABgBIAMg9IABABIgMA7IADACQAAACAAADIgBAAIgDgBg");
	this.shape_51.setTransform(6.9,11.9);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AAIAfQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIACgCIgZg4IABAAIAYA3IAEgBQABAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgCABIgCgBg");
	this.shape_52.setTransform(9.5,11.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAcAHIAAgCIg9gMIABgBIA7AMIACgEQACAAADABQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAABQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_53.setTransform(11.2,9.5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AAIAhIgKg8QgBABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgCgBAAgDQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIACABIABgBQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAIAKA+g");
	this.shape_54.setTransform(6.9,5.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgbAAQAAAAAAAAQAAAAAAAAQAAAAgBABQAAAAAAAAQgCACgDgCQAAAAgBgBQAAAAAAAAQAAAAAAAAQAAAAAAAAIABgBIAAgCIACgCQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIA/AGIgCABg");
	this.shape_55.setTransform(4.3,8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgYAVIgBgCQgBAAAAgBQAAAAgBgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAABAAIABAAIAyglIAAACIgwAkIACADQgBABAAABQAAAAgBABQAAAAgBAAQgBAAAAAAIgBABQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAg");
	this.shape_56.setTransform(4.9,10.7);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgfAMIA5gSQAAgBAAAAQgBgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAABABAAQAAABAAABQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAgBgBAAQAAgBgBgBIg7ATg");
	this.shape_57.setTransform(11.2,7.3);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgVAbIAlgvQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAgBQABAAAAgBQAAAAABgBQAAAAABAAQABgBAAAAQAAAAABABQAAAAAAAAQAAAAABABIABACIABABQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAIglAxg");
	this.shape_58.setTransform(10,5.6);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AAdABIg/ABIABgBIA9gBIABgCQABgCAEACQAAAAABAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgBAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBg");
	this.shape_59.setTransform(11.4,8.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AAEAhQgBABgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAIABgBIgJg+IABABIAJA7IAEABQACABgBAEIgCABIgCgBg");
	this.shape_60.setTransform(8.6,12);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgbATIAxggIgBgEQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAQABAAAAABQAAAAAAABQAAABAAABIABABQABABAAAAQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAgBgBAAQAAAAgBgBIg0Aig");
	this.shape_61.setTransform(10.8,6.6);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AggAIIgBgDIAAgCIAAgBQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABAAAAAAIABACIA+gJIgBABIg8AIIAAAEQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgBAAg");
	this.shape_62.setTransform(4.4,9.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AgEAhIAFg8QgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQgBgCACgDQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAAAAAIACABIABAAIACACQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIgFA/g");
	this.shape_63.setTransform(8.4,5.1);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgPgYQgDAEgBgFQgBAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAIABgBIgCgFIADAFIABgBQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABABQAAABAAAAQABABgBAAQAAABAAAAQgBABgBAAIAkA5IgBABg");
	this.shape_64.setTransform(5.7,5.3);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AAZAWQAAABAAABQgBAAAAAAQgBAAgBAAQAAAAgBgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQABAAAAAAIABgCIgygrIABAAIAxAqIACgBQAAgBABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABQABAAgBABQAAABAAAAQgBAAgBABIAFADg");
	this.shape_65.setTransform(10.8,11.1);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgVAbQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIACABIArg0IAAABIgpAzIADADQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAIgCAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBg");
	this.shape_66.setTransform(5.3,11.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.3,17);


(lib.lily = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAEkQABgDgBhdIAAh7QACg/AAgKIgCggIABgOQACgKgBgPQAAgngBgIQgDgKABgGQAAgDABgEIADgDQgDgCAAgGIgCgHIgFgBQgDgCgCgHQgCgMgGgKQgOgWgFgZQgBgFAHAFQAIAFAEAIQAGAKAMAbQgLg3gCgOQgDgfAGgDQADgBAGANQAEAMACALQAEAXABAhIAAAVIABAMIAGAVQAJgUABgLIACgLQgCgBgDgGQgEgKgBgTQAAgQgCgIQgBgHAAgKQAAgGAFAEQAFAEAFAKQAGALAEAVQAEAXgFALQgTAsgBAJQgFAUACAmIAAATQgBADAAADQABASgBAMIgBAcQABAUgCAJQgCALAAArQAAAmABASIACCSg");
	this.shape.setTransform(4.1,29.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,8.1,58.5);


(lib.grass = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLB2QgCgnAAgzQAAgfANg9IAOg1IgGAcQgHAjgBAjQgFA4AIBRg");
	this.shape.setTransform(4.4,31.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIBcQgCgiAAgoQAAgXAKgtIALgpIgFAVQgFAbgBAbQgEApAGBDg");
	this.shape_1.setTransform(11.4,33.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAABxQAEhPgEg0QgBgigGgiIgFgaIAMAzQALA5AAAeQAAAyACAlg");
	this.shape_2.setTransform(5.9,31.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAABxQAEhPgEg0QgBgigGgiIgFgaIAMAzQALA5AAAeQAAAyACAlg");
	this.shape_3.setTransform(11.6,31.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAFgRQgFgkgNgpIgNgjIAQAdQAQAnAIAyQAMBPABA9IgLABQgChbgJg4g");
	this.shape_4.setTransform(2.8,30.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJDWQAJjrgEhgIgHhgIAIAvQAIA+ABBJQAEByACCDg");
	this.shape_5.setTransform(7.8,21.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,43.3);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Butterfly = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Isolation Mode
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhyBtQgDgFAAgDIgFgBQgUgKAPgUQAYgXAIgMQAOgUAYgEQAXgDARALQgSgTANgVQACgDAdgjQAGgHAWgkQAVgbAOAbQARAggpAeIgIAGIAAADQACAPgQAQQgJAGgKAHIACACIAAABIAVgLQAUgGAMAEIAFgDQAogbAUAXQASASgfAMQgoAKgKADQgeAOgOADQgXAFgKgZQAIAYgYAZQgYAagcAAQgHAAgMAFIgCAAQgFAAgHgHgAhTBUQAVgIAEgJgAAeAHIgUALQgBAHgJAGQARADArgeQgEgCgFAAQgJAAgMAFgAgJASIAGgEQAFgDAEABIASgNQAQgQgCgNIAAgCIgGAFQAAADgEADIgCABIgFABQgZAWgFAPgAAYgVIABAAIACgBIADgEIgGAFg");
	this.shape.setTransform(21,25.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(1).to({_off:true},1).wait(4));

	// Isolation Mode
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah5ByQgDgEAAgEIgEgBQgWgKADghQACgaAQgWQANgSAZgFQAXgDARALQgSgUANgVIAhgnQAGgHAUgjQAVgbAOAbQASAhgcAqIgKAPQAJgDAFAHQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQACANgQAQIgSAPIABACIABABQAJgGALgFQAWgIAMAGQAAAAABABQAAAAABAAQAAABAAAAQABAAAAABQACADAAAEIAIgEQAzgPAVAWQASAUggALQgnAKgKAEQgeAOgOACQgZAFgKgYQAIAXgWAZQgYAagcAAQgjAAgUgYgAhGBMIgTANQAVgHADgJgAhZBGIAFgDIALgHQgHABgJAJgAAYANQgLAEgKAHQAAAHgJAFQAJACAkgMQgBgEADgDIACgDQAEgCAFACIABABQABABAAAAQAAABAAAAQAAABAAAAQAAABAAABIAGgCQAAgEgCgDIgDgCQgFgDgHAAQgIAAgLAFgAAsASIgCACQgCADABADIADgBQAAgBgBgBQAAAAAAgBQABAAAAgBQAAgBAAAAIACAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQABAAAAAAIAAABIAGgCQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAIgBgCIgCAAIgEABgAgPAXIAGgDQAGgDADABQALgJAHgHQAPgPgCgLIgBgEQgEgHgJAEIgBABIgGAJIAAABIABACQACAEAFgBIACgCQAEgCgBgDIgBgBQAAgBAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAIgBABQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAIABAAIACABQABAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgBABQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBIgBgCQAAgCADgDIABgBQAFgBACADIABACQABAEgFAEIgCABQgGADgEgGIgBgCQgVAhgCAJg");
	this.shape_1.setTransform(20.9,25.4);
	this.shape_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(4).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2));

	// Isolation Mode
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhfCdQgNgQAUgeIAggvIgGADQgLAJgRAJQgSAMgEgEQgIgGAtgeIALgGIgvALQgdAHgNgGQgWgMADgfQACgZAQgXQANgTAZgEQAXgEARALQgSgTANgXIAhgmQAGgGAWgkQAUgcANAcQATAkgNA4QgHAfgTA5IAGgDQAFgEAEACQANgJAFgFQAPgQgBgMIgBgEQgFgGgIADIgDABQgGAEACAGIAAACQADAEAFgBIACgBQAEgEgBgDIgBAAQAAgBgBgBQAAAAgBAAQAAAAgBAAQgBAAAAAAIgBABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAAIADABQAAAAAAAAQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAQgDABgCgCIAAgCQAAgDACgCIACgBQAFgBACADIABACQABAFgFADIgCABQgHACgDgEIgBgDQgCgIAHgFIAEgBQAKgEAFAIIABAEQACAOgQAQQgJAHgKAHIACACIAAABQAIgGANgFQAVgGAMAEQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAGAHgHAIIgDADQgIAEgGgEIgCgBQgDgGAFgEIABgCQAFgEAEADIACACQACACgDAEIgBACQgDACgEgCIAAgBQgCgCACgDQAAAAAAgBQAAAAAAAAQABAAAAAAQAAABABAAIAAABQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAIABABQAAAAAAABQABAAAAAAQABAAAAAAQABgBABAAIAAgBQADgCgCgCIgBgBQgDgCgDACIgCACQgDADACAFIACABQAEADAHgDIACgDQAGgHgEgGIgDgCQgMgEgUAFQgLAFgKAHQAAAGgLAGQAYAEBAABQA4AHAYAaQARAUgfALQgoAKgKAEQgeAOgOADQgYAEgLgYQAIAXgYAaQgVAZgdAAQgjAAgTgYg");
	this.shape_2.setTransform(20.6,24.9);
	this.shape_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2).to({_off:false},0).to({_off:true},2).wait(6).to({_off:false},0).wait(2));

	// Layer 1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ah6DJQgQgVAagnIAog8IgHAFIgkAXQgYAPgFgFQgGgFAWgSQAOgLASgMIAOgIIg8AOQglAJgRgIQgcgOAEgpQADggAUgcQARgZAggGQAdgEAWANQgXgYAQgcQACgDApgvQAHgIAcguQAagiARAiQAYAvgQBHQgJAogZBKIAHgFQAHgFAFACQAQgLAIgHQATgTgCgRIgBgFQgFgHgMADIgDACQgIAFACAIIABACQAEAFAGgCIACgBQAFgDgCgFIAAgBQgCgDgEABIgBABQgBAAgBABQAAAAAAABQAAABgBAAQAAABABAAIAAABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIgBABQgFABgBgDIgBgBQgBgFAEgCIACgBQAGgCADAEIABACQABAGgGAFIgDABQgIADgEgGQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgJAIgGIAFgCQAFgCAGABQAFACADAEQACADAAACQACASgVAVQgKAIgNAKIACACIAAABQAPgJAMgEQAagKAQAHQADABACADQACAEAAAFQgBAGgEAEIgEADQgIAHgJgGIgCgCQgFgGAGgHIADgCQAGgFAFAEIACACQADAEgEAFIgCABQgEADgEgDIgBgBQgCgDADgDIACAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAAAAAABIABAAQABABAAAAQABAAAAAAQABAAAAAAQABAAABgBIABgBQADgDgCgDIgCgBQgDgDgFADIgCACQgEAGADAEIACACQAHAFAHgFIADgDQAHgJgFgIQAAAAgBgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQgPgGgaAJQgMAFgOAJQAAAIgOAIQAeAEBRADQBIAHAeAiQAXAZgoAPQgzAMgNAFQgmASgSADQgfAGgNgfQAJAegeAhQgcAggkAAIgDAAQgrAAgYgeg");
	this.shape_3.setTransform(22.2,23.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).to({_off:true},2).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,44.5,46.3);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol9();
	this.instance.setTransform(15.4,8.1,1,1,0,0,0,15.4,8.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.9,16.1);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol5();
	this.instance.setTransform(3,42.2,1,1,0,0,0,3,42.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,7.1,85.5);


(lib.rose = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Symbol8();
	this.instance.setTransform(77.8,34.1,1,1,0,0,0,6.9,7.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:7,rotation:14.9,x:81,y:33.7},22).wait(2).to({regX:6.9,rotation:0,x:77.8,y:34.1},22,cjs.Ease.get(-0.3)).to({regY:7.7,rotation:-8.5,x:76.3,y:34.2},22).to({regY:7.6,rotation:0,x:77.8,y:34.1},22).wait(1));

	// Layer 3
	this.instance_1 = new lib.Symbol10();
	this.instance_1.setTransform(79.1,80.2,1,1,0,0,0,13.2,14.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:6.7,x:79.5},22).wait(2).to({rotation:0,x:79.1},22,cjs.Ease.get(-0.3)).to({rotation:-3.5,x:78.4},22).to({rotation:0,x:79.1},22).wait(1));

	// Layer 1
	this.instance_2 = new lib.Symbol11();
	this.instance_2.setTransform(79.3,93,1,1,0,0,0,79.3,93);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regY:93.1,rotation:3,y:93.2},22,cjs.Ease.get(0.3)).wait(2).to({regY:93,rotation:0,y:93},22,cjs.Ease.get(-0.3)).to({regX:79.2,rotation:-1.7,x:79.2},22,cjs.Ease.get(0.3)).to({regX:79.3,rotation:0,x:79.3},22).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(65.9,26.5,30.8,68);


(lib.longerplant = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Tween4("synched",0);
	this.instance.setTransform(10.2,119,1,1,0,0,0,-9.5,60);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:2.7,x:10.1},18,cjs.Ease.get(-0.4)).to({regY:60.1,rotation:-1.7,y:119.1},32).to({regY:60,rotation:0,x:10.2,y:119},24).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.3,117.9);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol6();
	this.instance.setTransform(3,42.2,1,1,0,0,0,3,42.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,7.1,85.5);


(lib.dandelion = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Symbol4();
	this.instance.setTransform(8.1,8.5,1,1,0,0,0,8.1,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:15,x:12.3,y:9.6},19,cjs.Ease.get(0.3)).wait(2).to({rotation:0,x:8.1,y:8.5},18,cjs.Ease.get(-0.3)).to({regY:8.6,rotation:-15,x:0.7,y:8.9},18,cjs.Ease.get(0.3)).wait(2).to({regY:8.5,rotation:0,x:8.1,y:8.5},18).wait(1));

	// Layer 1
	this.instance_1 = new lib.Symbol7();
	this.instance_1.setTransform(2.1,93.3,1,1,0,0,0,0,84.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,rotation:3},19,cjs.Ease.get(0.3)).wait(2).to({regX:0,rotation:0},18,cjs.Ease.get(-0.3)).to({regX:-0.1,rotation:-4.7},18,cjs.Ease.get(0.33)).wait(2).to({regX:0,rotation:0},18).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.3,93.7);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Bfly
	this.instance = new lib.Butterfly();
	this.instance.setTransform(-24.4,-8.9,0.596,0.596,0,0,0,22.2,23.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:41.3,y:2.1},30,cjs.Ease.get(0.6)).wait(3).to({x:163.3,y:50.1},38,cjs.Ease.get(0.5)).wait(3).to({x:215.3,y:30.1},31,cjs.Ease.get(0.3)).wait(3).to({x:212.3,y:26.6},0).wait(1).to({skewY:180,x:206.4},0).to({x:-60.6,y:-63.4},45).wait(16).to({x:1620.3,y:13.8},0).to({scaleX:0.6,scaleY:0.6,x:1455.8,y:-5.5},38,cjs.Ease.get(-0.2)).to({scaleX:0.6,scaleY:0.6,x:1451.3,y:1.8},2).wait(5).to({x:1455.8,y:8.2},0).to({x:1081.7,y:31.2},46,cjs.Ease.get(0.3)).to({x:855,y:37.7},49,cjs.Ease.get(0.62)).to({scaleX:0.6,scaleY:0.6,skewY:0,x:861.3,y:36.9},1,cjs.Ease.get(-0.5)).to({x:1532.2,y:-65.1},59).to({_off:true},1).wait(123));

	// Layer 1
	this.instance_1 = new lib.lily();
	this.instance_1.setTransform(1057.8,110.1,1,1,0,0,0,4,29.2);

	this.instance_2 = new lib.grass();
	this.instance_2.setTransform(1009.4,99.4,1,1,0,0,0,6.5,21.7);

	this.instance_3 = new lib.grass();
	this.instance_3.setTransform(1029.5,100.6,1,1,0,0,0,6.5,21.7);

	this.instance_4 = new lib.lily();
	this.instance_4.setTransform(979.8,101.3,1,1,0,0,0,4,29.2);

	this.instance_5 = new lib.lily();
	this.instance_5.setTransform(996.5,105.3,1,1,0,0,0,4,29.2);

	this.instance_6 = new lib.rose();
	this.instance_6.setTransform(968.5,100.6,1,1,0,0,0,81.3,60.5);

	this.instance_7 = new lib.rose();
	this.instance_7.setTransform(1038.4,88.8,1,1,0,0,0,81.3,60.5);

	this.instance_8 = new lib.weed();
	this.instance_8.setTransform(984.1,108.6,1,1,0,0,0,8.3,18.8);

	this.instance_9 = new lib.lily();
	this.instance_9.setTransform(1018.6,105.8,1,1,0,0,0,4,29.2);

	this.instance_10 = new lib.rose();
	this.instance_10.setTransform(1007.3,105.1,1,1,0,0,0,81.3,60.5);

	this.instance_11 = new lib.weed();
	this.instance_11.setTransform(1022.9,113.1,1,1,0,0,0,8.3,18.8);

	this.instance_12 = new lib.grass();
	this.instance_12.setTransform(995.9,117.6,1,1,0,0,0,6.5,21.7);

	this.instance_13 = new lib.lily();
	this.instance_13.setTransform(978,104.5,1,1,0,0,0,4,29.2);

	this.instance_14 = new lib.lily();
	this.instance_14.setTransform(1090.8,98.5,1,1,0,0,0,4,29.2);

	this.instance_15 = new lib.dandelion();
	this.instance_15.setTransform(1081.1,78.1,1,1,0,0,0,8.1,46.9);

	this.instance_16 = new lib.grass();
	this.instance_16.setTransform(1318.9,99.4,1,1,0,0,0,6.5,21.7);

	this.instance_17 = new lib.grass();
	this.instance_17.setTransform(1339,100.6,1,1,0,0,0,6.5,21.7);

	this.instance_18 = new lib.lily();
	this.instance_18.setTransform(1289.3,101.3,1,1,0,0,0,4,29.2);

	this.instance_19 = new lib.lily();
	this.instance_19.setTransform(1367.3,110.1,1,1,0,0,0,4,29.2);

	this.instance_20 = new lib.lily();
	this.instance_20.setTransform(1359.2,105.3,1,1,0,0,0,4,29.2);

	this.instance_21 = new lib.lily();
	this.instance_21.setTransform(1306,105.3,1,1,0,0,0,4,29.2);

	this.instance_22 = new lib.rose();
	this.instance_22.setTransform(1278,100.6,1,1,0,0,0,81.3,60.5);

	this.instance_23 = new lib.rose();
	this.instance_23.setTransform(1347.9,88.8,1,1,0,0,0,81.3,60.5);

	this.instance_24 = new lib.weed();
	this.instance_24.setTransform(1293.6,108.6,1,1,0,0,0,8.3,18.8);

	this.instance_25 = new lib.weed();
	this.instance_25.setTransform(1379.7,105.6,1,1,0,0,0,8.3,18.8);

	this.instance_26 = new lib.grass();
	this.instance_26.setTransform(1266.6,113.1,1,1,0,0,0,6.5,21.7);

	this.instance_27 = new lib.grass();
	this.instance_27.setTransform(1262.6,106.4,1,1,0,0,0,6.5,21.7);

	this.instance_28 = new lib.lily();
	this.instance_28.setTransform(946,99.8,1,1,0,0,0,4,29.2);

	this.instance_29 = new lib.dandelion();
	this.instance_29.setTransform(1428,75.4,1,1,0,0,180,8.1,46.9);

	this.instance_30 = new lib.grass();
	this.instance_30.setTransform(1457,103.3,1,1,0,0,180,6.5,21.7);

	this.instance_31 = new lib.grass();
	this.instance_31.setTransform(1403,104.5,1,1,0,0,180,6.5,21.7);

	this.instance_32 = new lib.lily();
	this.instance_32.setTransform(1390.1,105.2,1,1,0,0,180,4,29.2);

	this.instance_33 = new lib.lily();
	this.instance_33.setTransform(1446.6,95.5,1,1,0,0,180,4,29.2);

	this.instance_34 = new lib.longerplant();
	this.instance_34.setTransform(1474,67.2,1,1,0,0,180,19.7,59);

	this.instance_35 = new lib.rose();
	this.instance_35.setTransform(1401.5,104.5,1,1,0,0,180,81.3,60.5);

	this.instance_36 = new lib.rose();
	this.instance_36.setTransform(1415.9,94.9,1,1,0,0,180,81.3,60.5);

	this.instance_37 = new lib.weed();
	this.instance_37.setTransform(1385.8,112.5,1,1,0,0,180,8.3,18.8);

	this.instance_38 = new lib.weed();
	this.instance_38.setTransform(1439.6,109.5,1,1,0,0,0,8.3,18.8);

	this.instance_39 = new lib.weed();
	this.instance_39.setTransform(1468.1,109.4,1,1,0,0,180,8.3,18.8);

	this.instance_40 = new lib.rose();
	this.instance_40.setTransform(1250.9,85.5,1,1,0,0,0,81.3,60.5);

	this.instance_41 = new lib.grass();
	this.instance_41.setTransform(1252,107.5,1,1,0,0,0,6.5,21.7);

	this.instance_42 = new lib.grass();
	this.instance_42.setTransform(1244.5,107.5,1,1,0,0,0,6.5,21.7);

	this.instance_43 = new lib.grass();
	this.instance_43.setTransform(1239.1,101.1,1,1,0,0,0,6.5,21.7);

	this.instance_44 = new lib.grass();
	this.instance_44.setTransform(1226.2,107.5,1,1,0,0,0,6.5,21.7);

	this.instance_45 = new lib.grass();
	this.instance_45.setTransform(1231.6,101.4,1,1,0,0,0,6.5,21.7);

	this.instance_46 = new lib.grass();
	this.instance_46.setTransform(1218.7,107.5,1,1,0,0,0,6.5,21.7);

	this.instance_47 = new lib.grass();
	this.instance_47.setTransform(1213.3,101.1,1,1,0,0,0,6.5,21.7);

	this.instance_48 = new lib.dandelion();
	this.instance_48.setTransform(1193.7,79.9,1,1,0,0,0,8.1,46.9);

	this.instance_49 = new lib.grass();
	this.instance_49.setTransform(1147.4,104.6,1,1,0,0,0,6.5,21.7);

	this.instance_50 = new lib.grass();
	this.instance_50.setTransform(1143.5,97.9,1,1,0,0,0,6.5,21.7);

	this.instance_51 = new lib.lily();
	this.instance_51.setTransform(1129.6,103,1,1,0,0,0,4,29.2);

	this.instance_52 = new lib.lily();
	this.instance_52.setTransform(1202.7,110.7,1,1,0,0,0,4,29.2);

	this.instance_53 = new lib.rose();
	this.instance_53.setTransform(1174.7,106,1,1,0,0,0,81.3,60.5);

	this.instance_54 = new lib.dandelion();
	this.instance_54.setTransform(1119.9,82.6,1,1,0,0,0,8.1,46.9);

	this.instance_55 = new lib.grass();
	this.instance_55.setTransform(1357.7,103.9,1,1,0,0,0,6.5,21.7);

	this.instance_56 = new lib.grass();
	this.instance_56.setTransform(1377.8,105.1,1,1,0,0,0,6.5,21.7);

	this.instance_57 = new lib.lily();
	this.instance_57.setTransform(1328.1,105.8,1,1,0,0,0,4,29.2);

	this.instance_58 = new lib.lily();
	this.instance_58.setTransform(1088.9,114.6,1,1,0,0,0,4,29.2);

	this.instance_59 = new lib.lily();
	this.instance_59.setTransform(1080.8,109.8,1,1,0,0,0,4,29.2);

	this.instance_60 = new lib.lily();
	this.instance_60.setTransform(1344.8,109.8,1,1,0,0,0,4,29.2);

	this.instance_61 = new lib.rose();
	this.instance_61.setTransform(1316.8,105.1,1,1,0,0,0,81.3,60.5);

	this.instance_62 = new lib.rose();
	this.instance_62.setTransform(1386.7,93.3,1,1,0,0,0,81.3,60.5);

	this.instance_63 = new lib.weed();
	this.instance_63.setTransform(1332.4,113.1,1,1,0,0,0,8.3,18.8);

	this.instance_64 = new lib.weed();
	this.instance_64.setTransform(1101.3,110.1,1,1,0,0,0,8.3,18.8);

	this.instance_65 = new lib.grass();
	this.instance_65.setTransform(1305.4,117.6,1,1,0,0,0,6.5,21.7);

	this.instance_66 = new lib.grass();
	this.instance_66.setTransform(1257.4,107.5,1,1,0,0,0,6.5,21.7);

	this.instance_67 = new lib.lily();
	this.instance_67.setTransform(1287.5,104.5,1,1,0,0,0,4,29.2);

	this.instance_68 = new lib.dandelion();
	this.instance_68.setTransform(1277.9,78.1,1,1,0,0,0,8.1,46.9);

	this.instance_69 = new lib.grass();
	this.instance_69.setTransform(881.2,99.4,1,1,0,0,0,6.5,21.7);

	this.instance_70 = new lib.grass();
	this.instance_70.setTransform(901.2,100.6,1,1,0,0,0,6.5,21.7);

	this.instance_71 = new lib.lily();
	this.instance_71.setTransform(851.6,101.3,1,1,0,0,0,4,29.2);

	this.instance_72 = new lib.lily();
	this.instance_72.setTransform(929.6,110.1,1,1,0,0,0,4,29.2);

	this.instance_73 = new lib.lily();
	this.instance_73.setTransform(921.5,105.3,1,1,0,0,0,4,29.2);

	this.instance_74 = new lib.lily();
	this.instance_74.setTransform(868.2,105.3,1,1,0,0,0,4,29.2);

	this.instance_75 = new lib.rose();
	this.instance_75.setTransform(840.2,100.6,1,1,0,0,0,81.3,60.5);

	this.instance_76 = new lib.rose();
	this.instance_76.setTransform(910.1,88.8,1,1,0,0,0,81.3,60.5);

	this.instance_77 = new lib.weed();
	this.instance_77.setTransform(855.9,108.6,1,1,0,0,0,8.3,18.8);

	this.instance_78 = new lib.weed();
	this.instance_78.setTransform(1259.2,105.6,1,1,0,0,0,8.3,18.8);

	this.instance_79 = new lib.grass();
	this.instance_79.setTransform(881.9,109.7,1,1,0,0,0,6.5,21.7);

	this.instance_80 = new lib.grass();
	this.instance_80.setTransform(878,103,1,1,0,0,0,6.5,21.7);

	this.instance_81 = new lib.lily();
	this.instance_81.setTransform(864.1,102.1,1,1,0,0,0,4,29.2);

	this.instance_82 = new lib.dandelion();
	this.instance_82.setTransform(854.4,81.7,1,1,0,0,0,8.1,46.9);

	this.instance_83 = new lib.grass();
	this.instance_83.setTransform(775,103,1,1,0,0,0,6.5,21.7);

	this.instance_84 = new lib.grass();
	this.instance_84.setTransform(795,104.2,1,1,0,0,0,6.5,21.7);

	this.instance_85 = new lib.lily();
	this.instance_85.setTransform(745.4,104.9,1,1,0,0,0,4,29.2);

	this.instance_86 = new lib.lily();
	this.instance_86.setTransform(823.4,113.7,1,1,0,0,0,4,29.2);

	this.instance_87 = new lib.lily();
	this.instance_87.setTransform(815.3,108.9,1,1,0,0,0,4,29.2);

	this.instance_88 = new lib.lily();
	this.instance_88.setTransform(762,108.9,1,1,0,0,0,4,29.2);

	this.instance_89 = new lib.rose();
	this.instance_89.setTransform(734,104.2,1,1,0,0,0,81.3,60.5);

	this.instance_90 = new lib.rose();
	this.instance_90.setTransform(803.9,92.4,1,1,0,0,0,81.3,60.5);

	this.instance_91 = new lib.weed();
	this.instance_91.setTransform(749.7,112.2,1,1,0,0,0,8.3,18.8);

	this.instance_92 = new lib.weed();
	this.instance_92.setTransform(835.8,109.2,1,1,0,0,0,8.3,18.8);

	this.instance_93 = new lib.rose();
	this.instance_93.setTransform(437.4,90.9,1,1,0,0,180,81.3,60.5);

	this.instance_94 = new lib.grass();
	this.instance_94.setTransform(389.8,119.2,1,1,0,0,180,6.5,21.7);

	this.instance_95 = new lib.grass();
	this.instance_95.setTransform(384.4,113.1,1,1,0,0,180,6.5,21.7);

	this.instance_96 = new lib.grass();
	this.instance_96.setTransform(397.3,119.2,1,1,0,0,180,6.5,21.7);

	this.instance_97 = new lib.grass();
	this.instance_97.setTransform(402.7,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_98 = new lib.grass();
	this.instance_98.setTransform(412.8,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_99 = new lib.grass();
	this.instance_99.setTransform(407.4,106.8,1,1,0,0,180,6.5,21.7);

	this.instance_100 = new lib.grass();
	this.instance_100.setTransform(420.3,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_101 = new lib.grass();
	this.instance_101.setTransform(425.7,106.5,1,1,0,0,180,6.5,21.7);

	this.instance_102 = new lib.grass();
	this.instance_102.setTransform(436.3,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_103 = new lib.grass();
	this.instance_103.setTransform(430.9,106.8,1,1,0,0,180,6.5,21.7);

	this.instance_104 = new lib.grass();
	this.instance_104.setTransform(443.8,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_105 = new lib.grass();
	this.instance_105.setTransform(449.2,106.5,1,1,0,0,180,6.5,21.7);

	this.instance_106 = new lib.grass();
	this.instance_106.setTransform(462.1,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_107 = new lib.grass();
	this.instance_107.setTransform(456.7,106.8,1,1,0,0,180,6.5,21.7);

	this.instance_108 = new lib.grass();
	this.instance_108.setTransform(469.6,112.9,1,1,0,0,180,6.5,21.7);

	this.instance_109 = new lib.grass();
	this.instance_109.setTransform(475,106.5,1,1,0,0,180,6.5,21.7);

	this.instance_110 = new lib.dandelion();
	this.instance_110.setTransform(494.7,85.3,1,1,0,0,180,8.1,46.9);

	this.instance_111 = new lib.grass();
	this.instance_111.setTransform(540.9,110,1,1,0,0,180,6.5,21.7);

	this.instance_112 = new lib.grass();
	this.instance_112.setTransform(544.9,103.3,1,1,0,0,180,6.5,21.7);

	this.instance_113 = new lib.lily();
	this.instance_113.setTransform(558.8,102.4,1,1,0,0,180,4,29.2);

	this.instance_114 = new lib.lily();
	this.instance_114.setTransform(485.6,116.1,1,1,0,0,180,4,29.2);

	this.instance_115 = new lib.rose();
	this.instance_115.setTransform(513.6,111.4,1,1,0,0,180,81.3,60.5);

	this.instance_116 = new lib.dandelion();
	this.instance_116.setTransform(568.4,82,1,1,0,0,180,8.1,46.9);

	this.instance_117 = new lib.grass();
	this.instance_117.setTransform(647.9,103.3,1,1,0,0,180,6.5,21.7);

	this.instance_118 = new lib.grass();
	this.instance_118.setTransform(627.8,104.5,1,1,0,0,180,6.5,21.7);

	this.instance_119 = new lib.grass();
	this.instance_119.setTransform(690.4,104.5,1,1,0,0,180,6.5,21.7);

	this.instance_120 = new lib.lily();
	this.instance_120.setTransform(677.5,105.2,1,1,0,0,180,4,29.2);

	this.instance_121 = new lib.lily();
	this.instance_121.setTransform(599.5,114,1,1,0,0,180,4,29.2);

	this.instance_122 = new lib.lily();
	this.instance_122.setTransform(607.6,109.2,1,1,0,0,180,4,29.2);

	this.instance_123 = new lib.lily();
	this.instance_123.setTransform(660.8,109.2,1,1,0,0,180,4,29.2);

	this.instance_124 = new lib.rose();
	this.instance_124.setTransform(688.8,104.5,1,1,0,0,180,81.3,60.5);

	this.instance_125 = new lib.rose();
	this.instance_125.setTransform(618.9,92.7,1,1,0,0,180,81.3,60.5);

	this.instance_126 = new lib.rose();
	this.instance_126.setTransform(703.2,94.9,1,1,0,0,180,81.3,60.5);

	this.instance_127 = new lib.weed();
	this.instance_127.setTransform(673.2,112.5,1,1,0,0,180,8.3,18.8);

	this.instance_128 = new lib.weed();
	this.instance_128.setTransform(587.1,109.5,1,1,0,0,180,8.3,18.8);

	this.instance_129 = new lib.rose();
	this.instance_129.setTransform(347,90.9,1,1,0,0,0,81.3,60.5);

	this.instance_130 = new lib.grass();
	this.instance_130.setTransform(394.6,119.2,1,1,0,0,0,6.5,21.7);

	this.instance_131 = new lib.grass();
	this.instance_131.setTransform(400,113.1,1,1,0,0,0,6.5,21.7);

	this.instance_132 = new lib.grass();
	this.instance_132.setTransform(387.1,119.2,1,1,0,0,0,6.5,21.7);

	this.instance_133 = new lib.grass();
	this.instance_133.setTransform(381.7,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_134 = new lib.grass();
	this.instance_134.setTransform(371.6,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_135 = new lib.grass();
	this.instance_135.setTransform(377,106.8,1,1,0,0,0,6.5,21.7);

	this.instance_136 = new lib.grass();
	this.instance_136.setTransform(364.1,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_137 = new lib.grass();
	this.instance_137.setTransform(358.7,106.5,1,1,0,0,0,6.5,21.7);

	this.instance_138 = new lib.grass();
	this.instance_138.setTransform(348.1,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_139 = new lib.grass();
	this.instance_139.setTransform(353.5,106.8,1,1,0,0,0,6.5,21.7);

	this.instance_140 = new lib.grass();
	this.instance_140.setTransform(340.6,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_141 = new lib.grass();
	this.instance_141.setTransform(335.2,106.5,1,1,0,0,0,6.5,21.7);

	this.instance_142 = new lib.grass();
	this.instance_142.setTransform(322.3,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_143 = new lib.grass();
	this.instance_143.setTransform(327.7,106.8,1,1,0,0,0,6.5,21.7);

	this.instance_144 = new lib.grass();
	this.instance_144.setTransform(314.8,112.9,1,1,0,0,0,6.5,21.7);

	this.instance_145 = new lib.grass();
	this.instance_145.setTransform(309.4,106.5,1,1,0,0,0,6.5,21.7);

	this.instance_146 = new lib.dandelion();
	this.instance_146.setTransform(289.8,85.3,1,1,0,0,0,8.1,46.9);

	this.instance_147 = new lib.grass();
	this.instance_147.setTransform(243.5,110,1,1,0,0,0,6.5,21.7);

	this.instance_148 = new lib.grass();
	this.instance_148.setTransform(239.6,103.3,1,1,0,0,0,6.5,21.7);

	this.instance_149 = new lib.lily();
	this.instance_149.setTransform(225.7,102.4,1,1,0,0,0,4,29.2);

	this.instance_150 = new lib.lily();
	this.instance_150.setTransform(298.8,116.1,1,1,0,0,0,4,29.2);

	this.instance_151 = new lib.rose();
	this.instance_151.setTransform(270.8,111.4,1,1,0,0,0,81.3,60.5);

	this.instance_152 = new lib.dandelion();
	this.instance_152.setTransform(216,82,1,1,0,0,0,8.1,46.9);

	this.instance_153 = new lib.dandelion();
	this.instance_153.setTransform(69.1,75.4,1,1,0,0,0,8.1,46.9);

	this.instance_154 = new lib.grass();
	this.instance_154.setTransform(136.6,103.3,1,1,0,0,0,6.5,21.7);

	this.instance_155 = new lib.grass();
	this.instance_155.setTransform(156.6,104.5,1,1,0,0,0,6.5,21.7);

	this.instance_156 = new lib.grass();
	this.instance_156.setTransform(40.1,103.3,1,1,0,0,0,6.5,21.7);

	this.instance_157 = new lib.grass();
	this.instance_157.setTransform(94.1,104.5,1,1,0,0,0,6.5,21.7);

	this.instance_158 = new lib.lily();
	this.instance_158.setTransform(107,105.2,1,1,0,0,0,4,29.2);

	this.instance_159 = new lib.lily();
	this.instance_159.setTransform(50.5,95.5,1,1,0,0,0,4,29.2);

	this.instance_160 = new lib.lily();
	this.instance_160.setTransform(185,114,1,1,0,0,0,4,29.2);

	this.instance_161 = new lib.lily();
	this.instance_161.setTransform(176.9,109.2,1,1,0,0,0,4,29.2);

	this.instance_162 = new lib.lily();
	this.instance_162.setTransform(123.6,109.2,1,1,0,0,0,4,29.2);

	this.instance_163 = new lib.longerplant();
	this.instance_163.setTransform(23.1,67.2,1,1,0,0,0,19.7,59);

	this.instance_164 = new lib.rose();
	this.instance_164.setTransform(95.6,104.5,1,1,0,0,0,81.3,60.5);

	this.instance_165 = new lib.rose();
	this.instance_165.setTransform(165.5,92.7,1,1,0,0,0,81.3,60.5);

	this.instance_166 = new lib.rose();
	this.instance_166.setTransform(81.2,94.9,1,1,0,0,0,81.3,60.5);

	this.instance_167 = new lib.weed();
	this.instance_167.setTransform(111.3,112.5,1,1,0,0,0,8.3,18.8);

	this.instance_168 = new lib.weed();
	this.instance_168.setTransform(197.4,109.5,1,1,0,0,0,8.3,18.8);

	this.instance_169 = new lib.weed();
	this.instance_169.setTransform(57.5,109.5,1,1,0,0,180,8.3,18.8);

	this.instance_170 = new lib.weed();
	this.instance_170.setTransform(29,109.4,1,1,0,0,0,8.3,18.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_170},{t:this.instance_169},{t:this.instance_168},{t:this.instance_167},{t:this.instance_166},{t:this.instance_165},{t:this.instance_164},{t:this.instance_163},{t:this.instance_162},{t:this.instance_161},{t:this.instance_160},{t:this.instance_159},{t:this.instance_158},{t:this.instance_157},{t:this.instance_156},{t:this.instance_155},{t:this.instance_154},{t:this.instance_153},{t:this.instance_152},{t:this.instance_151},{t:this.instance_150},{t:this.instance_149},{t:this.instance_148},{t:this.instance_147},{t:this.instance_146},{t:this.instance_145},{t:this.instance_144},{t:this.instance_143},{t:this.instance_142},{t:this.instance_141},{t:this.instance_140},{t:this.instance_139},{t:this.instance_138},{t:this.instance_137},{t:this.instance_136},{t:this.instance_135},{t:this.instance_134},{t:this.instance_133},{t:this.instance_132},{t:this.instance_131},{t:this.instance_130},{t:this.instance_129},{t:this.instance_128},{t:this.instance_127},{t:this.instance_126},{t:this.instance_125},{t:this.instance_124},{t:this.instance_123},{t:this.instance_122},{t:this.instance_121},{t:this.instance_120},{t:this.instance_119},{t:this.instance_118},{t:this.instance_117},{t:this.instance_116},{t:this.instance_115},{t:this.instance_114},{t:this.instance_113},{t:this.instance_112},{t:this.instance_111},{t:this.instance_110},{t:this.instance_109},{t:this.instance_108},{t:this.instance_107},{t:this.instance_106},{t:this.instance_105},{t:this.instance_104},{t:this.instance_103},{t:this.instance_102},{t:this.instance_101},{t:this.instance_100},{t:this.instance_99},{t:this.instance_98},{t:this.instance_97},{t:this.instance_96},{t:this.instance_95},{t:this.instance_94},{t:this.instance_93},{t:this.instance_92},{t:this.instance_91},{t:this.instance_90},{t:this.instance_89},{t:this.instance_88},{t:this.instance_87},{t:this.instance_86},{t:this.instance_85},{t:this.instance_84},{t:this.instance_83},{t:this.instance_82},{t:this.instance_81},{t:this.instance_80},{t:this.instance_79},{t:this.instance_78},{t:this.instance_77},{t:this.instance_76},{t:this.instance_75},{t:this.instance_74},{t:this.instance_73},{t:this.instance_72},{t:this.instance_71},{t:this.instance_70},{t:this.instance_69},{t:this.instance_68},{t:this.instance_67},{t:this.instance_66},{t:this.instance_65},{t:this.instance_64},{t:this.instance_63},{t:this.instance_62},{t:this.instance_61},{t:this.instance_60},{t:this.instance_59},{t:this.instance_58},{t:this.instance_57},{t:this.instance_56},{t:this.instance_55},{t:this.instance_54},{t:this.instance_53},{t:this.instance_52},{t:this.instance_51},{t:this.instance_50},{t:this.instance_49},{t:this.instance_48},{t:this.instance_47},{t:this.instance_46},{t:this.instance_45},{t:this.instance_44},{t:this.instance_43},{t:this.instance_42},{t:this.instance_41},{t:this.instance_40},{t:this.instance_39},{t:this.instance_38},{t:this.instance_37},{t:this.instance_36},{t:this.instance_35},{t:this.instance_34},{t:this.instance_33},{t:this.instance_32},{t:this.instance_31},{t:this.instance_30},{t:this.instance_29},{t:this.instance_28},{t:this.instance_27},{t:this.instance_26},{t:this.instance_25},{t:this.instance_24},{t:this.instance_23},{t:this.instance_22},{t:this.instance_21},{t:this.instance_20},{t:this.instance_19},{t:this.instance_18},{t:this.instance_17},{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]}).to({state:[{t:this.instance_170},{t:this.instance_169},{t:this.instance_168},{t:this.instance_167},{t:this.instance_166},{t:this.instance_165},{t:this.instance_164},{t:this.instance_163},{t:this.instance_162},{t:this.instance_161},{t:this.instance_160},{t:this.instance_159},{t:this.instance_158},{t:this.instance_157},{t:this.instance_156},{t:this.instance_155},{t:this.instance_154},{t:this.instance_153},{t:this.instance_152},{t:this.instance_151},{t:this.instance_150},{t:this.instance_149},{t:this.instance_148},{t:this.instance_147},{t:this.instance_146},{t:this.instance_145},{t:this.instance_144},{t:this.instance_143},{t:this.instance_142},{t:this.instance_141},{t:this.instance_140},{t:this.instance_139},{t:this.instance_138},{t:this.instance_137},{t:this.instance_136},{t:this.instance_135},{t:this.instance_134},{t:this.instance_133},{t:this.instance_132},{t:this.instance_131},{t:this.instance_130},{t:this.instance_129},{t:this.instance_128},{t:this.instance_127},{t:this.instance_126},{t:this.instance_125},{t:this.instance_124},{t:this.instance_123},{t:this.instance_122},{t:this.instance_121},{t:this.instance_120},{t:this.instance_119},{t:this.instance_118},{t:this.instance_117},{t:this.instance_116},{t:this.instance_115},{t:this.instance_114},{t:this.instance_113},{t:this.instance_112},{t:this.instance_111},{t:this.instance_110},{t:this.instance_109},{t:this.instance_108},{t:this.instance_107},{t:this.instance_106},{t:this.instance_105},{t:this.instance_104},{t:this.instance_103},{t:this.instance_102},{t:this.instance_101},{t:this.instance_100},{t:this.instance_99},{t:this.instance_98},{t:this.instance_97},{t:this.instance_96},{t:this.instance_95},{t:this.instance_94},{t:this.instance_93},{t:this.instance_92},{t:this.instance_91},{t:this.instance_90},{t:this.instance_89},{t:this.instance_88},{t:this.instance_87},{t:this.instance_86},{t:this.instance_85},{t:this.instance_84},{t:this.instance_83},{t:this.instance_82},{t:this.instance_81},{t:this.instance_80},{t:this.instance_79},{t:this.instance_78},{t:this.instance_77},{t:this.instance_76},{t:this.instance_75},{t:this.instance_74},{t:this.instance_73},{t:this.instance_72},{t:this.instance_71},{t:this.instance_70},{t:this.instance_69},{t:this.instance_68},{t:this.instance_67},{t:this.instance_66},{t:this.instance_65},{t:this.instance_64},{t:this.instance_63},{t:this.instance_62},{t:this.instance_61},{t:this.instance_60},{t:this.instance_59},{t:this.instance_58},{t:this.instance_57},{t:this.instance_56},{t:this.instance_55},{t:this.instance_54},{t:this.instance_53},{t:this.instance_52},{t:this.instance_51},{t:this.instance_50},{t:this.instance_49},{t:this.instance_48},{t:this.instance_47},{t:this.instance_46},{t:this.instance_45},{t:this.instance_44},{t:this.instance_43},{t:this.instance_42},{t:this.instance_41},{t:this.instance_40},{t:this.instance_39},{t:this.instance_38},{t:this.instance_37},{t:this.instance_36},{t:this.instance_35},{t:this.instance_34},{t:this.instance_33},{t:this.instance_32},{t:this.instance_31},{t:this.instance_30},{t:this.instance_29},{t:this.instance_28},{t:this.instance_27},{t:this.instance_26},{t:this.instance_25},{t:this.instance_24},{t:this.instance_23},{t:this.instance_22},{t:this.instance_21},{t:this.instance_20},{t:this.instance_19},{t:this.instance_18},{t:this.instance_17},{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]},195).wait(299));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.6,-22.7,1531.3,168);


// stage content:



(lib.footeranimation = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Page 1
	this.instance = new lib.ClipGroup();
	this.instance.setTransform(92.5,183,0.167,0.167,0,0,0,539.1,154.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Isolation Mode
	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(66.3,145.8,1,1,0,0,0,67.3,71.4);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(711.4,151.7,1531.3,168.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;